### PR TITLE
Scatter plot using data_set_labels

### PR DESCRIPTION
**Pull request by avonow**
This update includes:
- a new project folder within `examples` called `scatter`, which compiles a scatter plot
- revised README's with details on the development of a scatter plot
- some minor updates to horizontal_series.rs
- some new lines at the end of some files

### CODE REVIEW

**Review by huntc — CHANGES_REQUESTED** [review]
Fantastic! Thanks!

One last thing: can we make the bar charts a bit fatter in their appearance. This is achievable via css...

**Comment by huntc** [comment]
@avonow - Tests are failing. Please run `cargo clippy` to see why. Thanks!

**Review by huntc — APPROVED** [review]
Thank you for this steller contribution!

**Comment by avonow** [comment]
Thanks, @huntc! You're welcome.

**Pull request merged**
